inventaris/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.BarangList.as_view(), name='barang_list'),
    path('add', views.BarangAdd.as_view(), name='barang_add'),
    path('edit/<int:pk>', views.BarangUpdate.as_view(), name='barang_edit'),
    path('delete/<int:pk>', views.BarangDelete, name='barang_delete'),

    path('inv_list', views.InventoryList.as_view(), name='inventaris_list'),
    path('inv_add', views.InventoryAdd.as_view(), name='inventaris_add'),
    path('inv_edit/<int:pk>', views.InventoryUpdate.as_view(), name='inventaris_edit'),
    path('inv_delete/<int:pk>', views.InventoryDelete, name='inventaris_delete'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from inventaris import views
from account import views as acc_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.dashboard, name='dashboard'),
    path('inventaris/',include('inventaris.urls')),
    # path('login', acc_views.login_view, name='login'),
    # path('logout', auth_views.auth_logout, name='logout'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', acc_views.logout_view, name='logout'),
    path('daftar', acc_views.daftar, name='daftar'),
]

account/models.py
from django.db import models

# Create your models here.

inventaris/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Barang(models.Model):
    nama_barang = models.CharField(max_length=100)
    pembuat = models.CharField(max_length=100)
    jenis = models.CharField(max_length=100)
    spesifikasi = models.TextField()

    def __str__(self):
        return self.nama_barang

    class Meta:
        verbose_name_plural = "Daftar Barang"

STATUS_BARANG=(
    (1, 'Aktif'),
    (2, 'Rusak'),
    (3, 'Hilang'),
    (4, 'Dilelang'),
)

class Inventaris(models.Model):
    barang = models.ForeignKey(Barang, on_delete=models.CASCADE)
    no_inventaris = models.CharField(max_length=50)
    tanggal_pembelian = models.DateField()
    petugas_pengadaan = models.CharField(max_length=100)
    harga_pembelian = models.BigIntegerField()
    lokasi = models.CharField(max_length=100)
    tanggal_maintenance_terakhir = models.DateField(blank=True, null=True)
    nama_petugas_maintenance = models.CharField(max_length=100, null=True, blank=True)
    status_barang = models.IntegerField(choices=STATUS_BARANG, default=1)

    def __str__(self):
        return self.no_inventaris

    class Meta:
        verbose_name_plural = "Daftar Inventaris"

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class RegistrasiForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'password1','password2']
        labels = {'first_name': 'Nama'}
        help_texts = {
            'username': None,
        }

    def save(self, commit=True):
        user = super(RegistrasiForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']

        if commit:
            user.save()

        return user

account/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect


# Create your views here.
from account.forms import RegistrasiForm

def logout_view(request):
    logout(request)
    return redirect('/')

def daftar(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    elif request.method == 'POST':
        form = RegistrasiForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Berhasil Daftar!')
            return redirect('login')
    else:
        form = RegistrasiForm()

    data = {}
    data['form'] = form
    data['state'] = 'Daftar'
    return render(request, 'login.html', data)

inventaris/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from inventaris.models import Barang, Inventaris


def dashboard(request):
    return render(request, 'index.html',{})

@method_decorator(login_required, name='dispatch')
class BarangList(ListView):
    model = Barang
    context_object_name = 'data'

@method_decorator(login_required, name='dispatch')
class BarangAdd(CreateView):
    model = Barang
    fields = '__all__'
    success_url = reverse_lazy('barang_list')

@method_decorator(login_required, name='dispatch')
class BarangUpdate(UpdateView):
    model = Barang
    fields = '__all__'
    success_url = reverse_lazy('barang_list')

@login_required
def BarangDelete(request, pk):
    data = Barang.objects.get(pk = pk)
    data.delete()
    return redirect('barang_list')

########INVENTARIS########
@method_decorator(login_required, name='dispatch')
class InventoryList(ListView):
    model = Inventaris
    context_object_name = 'data'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = Inventaris.objects.all().aggregate(Sum('harga_pembelian'))
        return context

@method_decorator(login_required, name='dispatch')
class InventoryAdd(CreateView):
    model = Inventaris
    fields = '__all__'
    template_name = 'inventaris/barang_form.html'
    success_url = reverse_lazy('inventaris_list')

@method_decorator(login_required, name='dispatch')
class InventoryUpdate(UpdateView):
    model = Inventaris
    fields = '__all__'
    template_name = 'inventaris/barang_form.html'
    success_url = reverse_lazy('inventaris_list')

@login_required
def InventoryDelete(request, pk):
    data = Inventaris.objects.get(pk = pk)
    data.delete()
    return redirect('inventaris_list')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico"/>

    <title>{%block title%}Aplikasi Inventaris{%endblock%}</title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
    <!-- bootstrap-datetimepicker -->
    <link href="{% static 'vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
    <!-- Datatables -->
    <link href="{% static 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    {% block extracss %}
    {% endblock %}
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="{% url 'dashboard' %}" class="site_title"><i class="fa fa-cubes"></i> <span>SI Inventaris</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        <img src="/static/images/user.png" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Selamat Datang,</span>
                        <h2>{% if user.is_authenticated %}{{user}}{% endif %}</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br />
                {% if user.is_authenticated %}
                {% include 'sidebar.html' %}
                {% endif %}

            </div>
        </div>


        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                {{request.user}}
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Log Out</a>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        <li><a href="{% url 'login' %}">Log In <i class="fa fa-sign-in"></i> </a></li>
<!--                        <li><a href="{% url 'daftar' %}"> Daftar <i class="fa fa-arrows"></i></a></li>-->
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <!-- top tiles -->
            <div class="row">
                {%block content%}
                {%endblock%}
            </div>
            <!-- end of weather widget -->
        </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <footer>
        <div class="pull-right">©
            <script>
                                document.write(new Date().getFullYear())
            </script>
            <a href="https://www.ums.ac.id/">Universitas Muhammadiyah Surakarta</a></div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->
</div>

<!-- jQuery -->
<script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
<!-- Chart.js -->
<script src="{% static 'vendors/Chart.js/dist/Chart.min.js' %}"></script>
<!-- gauge.js -->
<script src="{% static 'vendors/gauge.js/dist/gauge.min.js' %}"></script>
<!-- bootstrap-progressbar -->
<script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
<!-- Skycons -->
<script src="{% static 'vendors/skycons/skycons.js' %}"></script>
<!-- Flot -->
<script src="{% static 'vendors/Flot/jquery.flot.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.time.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.stack.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.resize.js' %}"></script>
<!-- Flot plugins -->
<script src="{% static 'vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
<script src="{% static 'vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
<script src="{% static 'vendors/flot.curvedlines/curvedLines.js' %}"></script>
<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
<script src="{% static 'vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
<script src="{% static 'vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
<!-- bootstrap-daterangepicker -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- bootstrap-datetimepicker -->
<script src="{% static 'vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
<!-- Datatables -->
<script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
<script src="{% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
<script src="{% static 'vendors/jszip/dist/jszip.min.js' %}"></script>
<script src="{% static 'vendors/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'vendors/pdfmake/build/vfs_fonts.js' %}"></script>

<!-- Custom Theme Scripts -->
<script src="{% static 'build/js/custom.min.js' %}"></script>

<script type="text/javascript">
    {% block script %}
    {% endblock %}
</script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="card ">
			<div class="card-header ">
				<h1 class="card-title">Selamat Datang, {% if user.is_authenticated %}{{user}}{% endif %}</h1>
			</div>
			<div class="card-body ">
				<h1>Semoga harimu menyenangkan!</h1>
			</div>
		</div>
	</div>
</div>
{% endblock %}

<script>
{% block script %}
$(document).ready(function(){

});
{% endblock %}
</script>

templates/inventaris/barang_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h4>Tambah Data Barang</h4>
			</div>
			<div class="x_content ">
				<form method="POST" class="form-horizontal">
					<div class="form-group">
						{% csrf_token %}
						{{ form|crispy }}
					</div>
					<button type="submit" class="save btn btn-primary pull-right">Simpan</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

<script>
{% block script %}
$(document).ready(function(){
	//document.getElementById('id_tanggal_pembelian').type = 'date';
	//document.getElementById('id_tanggal_maintenance_terakhir').type = 'date';
	$('.dateinput').datetimepicker({
		format: 'YYYY-MM-DD'
	});
});
{% endblock %}
</script>

templates/inventaris/barang_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h4>Daftar Barang</h4>
			</div>
			<div class="x_content ">
				<a href="{% url 'barang_add' %}" class="btn btn-primary btn-fill pull-right">Tambah Barang</a>
				<table id="datatable" class="table table-hover table-striped">
					<thead>
					<tr>
						<th>No</th>
						<th>Nama Barang</th>
						<th>Pembuat</th>
						<th>Jenis</th>
						<th>Spesifikasi</th>
						<th>Aksi</th>
					</tr>
					</thead>
					<tbody>
					{% for d in data %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td>{{d.nama_barang}}</td>
						<td>{{d.pembuat}}</td>
						<td>{{d.jenis}}</td>
						<td>{{d.spesifikasi}}</td>
						<td>
							<div class="btn-group">
							<a href="{% url 'barang_edit' d.id %}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
							<a href="{% url 'barang_delete' d.id %}" class="btn btn-danger hapusItem"><i class="fa fa-trash"></i></a>
							</div>
						</td>
					</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

<script>
{% block script %}
	$(document).ready(function(){
		$(".hapusItem").click(function () {
				if(!confirm("Yakin ingin menghapus?")){
					return false;
				};
			});
	});
{% endblock %}
</script>

templates/inventaris/inventaris_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <a href="{% url 'inventaris_add' %}" class="btn btn-primary btn-fill pull-right">Tambah Inventaris</a>
                <h4 class="card-title">Daftar Inventaris</h4>
            </div>
            <div class="x_content">
                <table id="datatable" class="table table-hover table-striped" width="">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Barang</th>
                        <th>No Inventaris</th>
                        <th>Tgl Pembelian</th>
                        <th>Petugas Pengadaan</th>
                        <th>Harga Pembelian</th>
                        <th>Lokasi</th>
                        <th>Tgl Maintenance Terakhir</th>
                        <th>Petugas Maintenance</th>
                        <th>Status Barang</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for d in data %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{d.barang.nama_barang}}</td>
                        <td>{{d.no_inventaris}}</td>
                        <td>{{d.tanggal_pembelian}}</td>
                        <td>{{d.petugas_pengadaan}}</td>
                        <td>Rp {{d.harga_pembelian|intcomma}}</td>
                        <td>{{d.lokasi}}</td>
                        <td>{{d.tanggal_maintenance_terakhir|default_if_none:'-'}}</td>
                        <td>{{d.nama_petugas_maintenance|default_if_none:'-'}}</td>
                        <td>{{d.get_status_barang_display}}</td>
                        <td>
                            <div class="btn-group-vertical">
                                <a href="{% url 'inventaris_edit' d.id %}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                <a href="{% url 'inventaris_delete' d.id %}" class="btn btn-danger hapusItem"><i class="fa fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="9" align="right"><b>Total Asset</b></td>
                        <td colspan="2">Rp {{total.harga_pembelian__sum|intcomma}}</td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<script>
{% block script %}
	$(document).ready(function(){
		$(".hapusItem").click(function () {
				if(!confirm("Yakin ingin menghapus?")){
					return false;
				};
			});
	});
{% endblock %}

</script>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center">
	<div class="login_wrapper">
		<div class="animate form login_form">
			<section class="login_content">
				{% if messages %}
				{% for message in messages %}
				<div class="alert alert-success">
					<button class="close" data-close="alert"></button>
					<span>{{message}}</span>
				</div>
				{% endfor %}
				{% endif %}
				<form class="login-form" action="" method="post">
				<h1>Silahkan {% if state == 'Daftar' %} Daftar {% else %} Login {% endif %}</h1>
					{% csrf_token %}
					{{form|crispy}}
					<div class="form-actions">
						<button type="submit" class="btn btn-success pull-right"> Submit </button>
					</div>
				</form>
			</section>
		</div>
	</div>
	{% endblock %}

	{% block js %}
	<script>
$(document).ready(function(){
    $(".hapusItem").click(function () {
            if(!confirm("Yakin loooooh?")){
                return false;
            };
        });
});
</script>
	{% endblock js %}

templates/sidebar.html
<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> Menu <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="{% url 'barang_list' %}">Daftar Barang</a></li>
                    <li><a href="{% url 'inventaris_list' %}">Daftar Inventaris</a></li>
                </ul>
            </li>
        </ul>
    </div>

</div>
<!-- /sidebar menu -->